.TH "CLANNWebServiceController" 3 "Wed Jan 16 2013" "Version 1" "Web Service Module for Claroline" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLANNWebServiceController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetResourcesList\fP ()"
.br
.ti -1c
.RI "\fBgetSingleResource\fP ($args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file clannwebservicecontroller.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "getResourcesList ()"Returns all the announces of a course. 
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidArgumentException\fP if the $cid in not provided. 
.RE
.PP
\fBWeb Service call: /module/MOBILE/CLANN/getResourcesList/cidReq\fP
.RS 4

.RE
.PP
.PP
.nf
        Method : \fIgetResourcesList\fP
.fi
.PP
.PP
.PP
.nf
        cidReq : \fISYSCODE of requested cours\fP
.fi
.PP
.PP
\fBReturns:\fP
.RS 4
array of Announce object 
.RE
.PP

.PP
Definition at line 21 of file clannwebservicecontroller.lib.php.
.SS "getSingleResource ($args)"Returns a single resquested announce. 
.PP
\fBParameters:\fP
.RS 4
\fI$args\fP must contain 'resID' key with the resource identifier of the requested resource 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidArgumentException\fP if one of the paramaters is missing 
.RE
.PP
\fBWeb Service call: /module/MOBILE/CLANN/getSingleResource/cidReq/resId\fP
.RS 4

.RE
.PP
.PP
.nf
        Method : \fIgetSingleResource\fP
.fi
.PP
.PP
.PP
.nf
        cidReq : \fISYSCODE of requested cours\fP
.fi
.PP
.PP
.PP
.nf
        resID : \fIResource Id of requested resource\fP
.fi
.PP
.PP
\fBReturns:\fP
.RS 4
announce object (can be null if not visible for the current user) 
.RE
.PP

.PP
Definition at line 68 of file clannwebservicecontroller.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for Web Service Module for Claroline from the source code.
