.TH "MOBILE" 3 "Wed Jan 9 2013" "Version 1" "Web Service Module for Claroline" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MOBILE \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Web Services Provider Administration Library
.PP
\fBVersion:\fP
.RS 4
\fBMOBILE\fP 1 
.RE
.PP
\fBRevision:\fP
.RS 4
1 
.RE
.PP
- Claroline 1.11  2001-2012 Universite Catholique de Louvain (UCL)  http://www.gnu.org/copyleft/gpl.html (GPL) GENERAL PUBLIC LICENSE
.PP
\fBAuthor:\fP
.RS 4
Quentin Devos <q.devos@student.uclouvain.be>
.RE
.PP
Web Service Controller - Plugin Loader
.PP
2001-2013 Universite Catholique de Louvain (UCL)  http://www.gnu.org/copyleft/gpl.html (GPL) GENERAL PUBLIC LICENSE
.PP
\fBAuthor:\fP
.RS 4
Quentin Devos <q.devos@student.uclouvain.be>
.RE
.PP
Web Service Controller - CLANN library
.PP
2001-2013 Universite Catholique de Louvain (UCL)  http://www.gnu.org/copyleft/gpl.html (GPL) GENERAL PUBLIC LICENSE
.PP
\fBAuthor:\fP
.RS 4
Quentin Devos <q.devos@student.uclouvain.be>
.RE
.PP
Web Service Controller - CLDOC plugin
.PP
2001-2013 Universite Catholique de Louvain (UCL)  http://www.gnu.org/copyleft/gpl.html (GPL) GENERAL PUBLIC LICENSE
.PP
\fBAuthor:\fP
.RS 4
Quentin Devos <q.devos@student.uclouvain.be>
.RE
.PP
Web Service Controller - User plugin
.PP
2001-2013 Universite Catholique de Louvain (UCL)  http://www.gnu.org/copyleft/gpl.html (GPL) GENERAL PUBLIC LICENSE
.PP
\fBAuthor:\fP
.RS 4
Quentin Devos <q.devos@student.uclouvain.be> 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Web Service Module for Claroline from the source code.
